// <auto-generated />
namespace IneqApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Armando : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Armando));
        
        string IMigrationMetadata.Id
        {
            get { return "201609182318250_Armando"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
